"""Initial schema

Revision ID: ac5c912b8be6
Revises: 
Create Date: 2025-11-14 00:55:22.659810

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac5c912b8be6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crime_categories",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("harm_weight_default", sa.Float(), nullable=False),
        sa.Column("is_personal", sa.Boolean(), nullable=False),
        sa.Column("is_property", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("area_name", sa.String(length=100), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("records_ingested", sa.Integer(), nullable=False),
        sa.Column("tiles_processed", sa.Integer(), nullable=False),
        sa.Column("tiles_total", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_runs_area_month", "ingestion_runs", ["area_name", "month"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_runs_area_name"), "ingestion_runs", ["area_name"], unique=False
    )
    op.create_index(op.f("ix_ingestion_runs_month"), "ingestion_runs", ["month"], unique=False)
    op.create_index("ix_ingestion_runs_status", "ingestion_runs", ["status"], unique=False)
    op.create_table(
        "safety_cells",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cell_id", sa.String(length=200), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=27700,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("crime_count_total", sa.Integer(), nullable=False),
        sa.Column("crime_count_weighted", sa.Float(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # idx_safety_cells_geom is automatically created by GeoAlchemy2
    # op.create_index('idx_safety_cells_geom', 'safety_cells', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f("ix_safety_cells_cell_id"), "safety_cells", ["cell_id"], unique=True)
    op.create_index(
        "ix_safety_cells_geom", "safety_cells", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_safety_cells_month"), "safety_cells", ["month"], unique=False)
    op.create_index("ix_safety_cells_month_desc", "safety_cells", ["month"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_created_at", "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "crime_incidents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("category_id", sa.String(length=100), nullable=False),
        sa.Column("crime_type", sa.String(length=200), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("persistent_id", sa.String(length=200), nullable=True),
        sa.Column("lsoa_code", sa.String(length=100), nullable=True),
        sa.Column("force_id", sa.String(length=100), nullable=False),
        sa.Column("location_desc", sa.Text(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["crime_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # idx_crime_incidents_geom is automatically created by GeoAlchemy2
    # op.create_index('idx_crime_incidents_geom', 'crime_incidents', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(
        op.f("ix_crime_incidents_category_id"), "crime_incidents", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_crime_incidents_force_id"), "crime_incidents", ["force_id"], unique=False
    )
    op.create_index(
        "ix_crime_incidents_geom",
        "crime_incidents",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(op.f("ix_crime_incidents_month"), "crime_incidents", ["month"], unique=False)
    op.create_index(
        "ix_crime_incidents_month_category",
        "crime_incidents",
        ["month", "category_id"],
        unique=False,
    )
    op.create_index("ix_crime_incidents_month_desc", "crime_incidents", ["month"], unique=False)
    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_refresh_sessions_active",
        "refresh_sessions",
        ["user_id", "revoked_at"],
        unique=False,
        postgresql_where="revoked_at IS NULL",
    )
    op.create_index(
        "ix_refresh_sessions_expires_at", "refresh_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_refresh_sessions_token_hash", "refresh_sessions", ["token_hash"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id"), "refresh_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "route_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("origin_lat", sa.Float(), nullable=False),
        sa.Column("origin_lng", sa.Float(), nullable=False),
        sa.Column("destination_lat", sa.Float(), nullable=False),
        sa.Column("destination_lng", sa.Float(), nullable=False),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.Column("safety_score_best", sa.Float(), nullable=True),
        sa.Column("distance_m_best", sa.Integer(), nullable=True),
        sa.Column("duration_s_best", sa.Integer(), nullable=True),
        sa.Column("request_meta", sa.JSON(), nullable=False),
        sa.Column(
            "route_geom",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # idx_route_history_route_geom is automatically created by GeoAlchemy2
    # op.create_index('idx_route_history_route_geom', 'route_history', ['route_geom'], unique=False, postgresql_using='gist')
    op.create_index(
        "ix_route_history_active",
        "route_history",
        ["user_id", "deleted_at"],
        unique=False,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_index(
        "ix_route_history_geom",
        "route_history",
        ["route_geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_where="route_geom IS NOT NULL",
    )
    op.create_index(
        "ix_route_history_user_created", "route_history", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_route_history_user_id"), "route_history", ["user_id"], unique=False)
    # Don't drop spatial_ref_sys - it's managed by PostGIS
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't create spatial_ref_sys - it's managed by PostGIS
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_index(op.f("ix_route_history_user_id"), table_name="route_history")
    op.drop_index("ix_route_history_user_created", table_name="route_history")
    op.drop_index(
        "ix_route_history_geom",
        table_name="route_history",
        postgresql_using="gist",
        postgresql_where="route_geom IS NOT NULL",
    )
    op.drop_index(
        "ix_route_history_active", table_name="route_history", postgresql_where="deleted_at IS NULL"
    )
    op.drop_index(
        "idx_route_history_route_geom", table_name="route_history", postgresql_using="gist"
    )
    op.drop_table("route_history")
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_token_hash", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_expires_at", table_name="refresh_sessions")
    op.drop_index(
        "ix_refresh_sessions_active",
        table_name="refresh_sessions",
        postgresql_where="revoked_at IS NULL",
    )
    op.drop_table("refresh_sessions")
    op.drop_index("ix_crime_incidents_month_desc", table_name="crime_incidents")
    op.drop_index("ix_crime_incidents_month_category", table_name="crime_incidents")
    op.drop_index(op.f("ix_crime_incidents_month"), table_name="crime_incidents")
    op.drop_index("ix_crime_incidents_geom", table_name="crime_incidents", postgresql_using="gist")
    op.drop_index(op.f("ix_crime_incidents_force_id"), table_name="crime_incidents")
    op.drop_index(op.f("ix_crime_incidents_category_id"), table_name="crime_incidents")
    op.drop_index("idx_crime_incidents_geom", table_name="crime_incidents", postgresql_using="gist")
    op.drop_table("crime_incidents")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("ix_users_created_at", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_safety_cells_month_desc", table_name="safety_cells")
    op.drop_index(op.f("ix_safety_cells_month"), table_name="safety_cells")
    op.drop_index("ix_safety_cells_geom", table_name="safety_cells", postgresql_using="gist")
    op.drop_index(op.f("ix_safety_cells_cell_id"), table_name="safety_cells")
    op.drop_index("idx_safety_cells_geom", table_name="safety_cells", postgresql_using="gist")
    op.drop_table("safety_cells")
    op.drop_index("ix_ingestion_runs_status", table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_month"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_area_name"), table_name="ingestion_runs")
    op.drop_index("ix_ingestion_runs_area_month", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_table("crime_categories")
    # ### end Alembic commands ###
